// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_vviarVVMlKiXDSaqvD3dprF6lz_wvCY',
    appId: '1:808048469446:web:b4feb80229965c0e5e7ec7',
    messagingSenderId: '808048469446',
    projectId: 'cs5520-final-projec',
    authDomain: 'cs5520-final-projec.firebaseapp.com',
    storageBucket: 'cs5520-final-projec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWxs2pPRf5qGSKmHJfvVPXyATGL0VfHko',
    appId: '1:808048469446:android:f26d691c214344c85e7ec7',
    messagingSenderId: '808048469446',
    projectId: 'cs5520-final-projec',
    storageBucket: 'cs5520-final-projec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMPZvQt6YpkTyJYIGWn9B0UiDoOaSWV4A',
    appId: '1:808048469446:ios:9d26a871adb12dc75e7ec7',
    messagingSenderId: '808048469446',
    projectId: 'cs5520-final-projec',
    storageBucket: 'cs5520-final-projec.appspot.com',
    iosBundleId: 'com.example.discourse',
  );
}
